#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Aug  3 18:02:13 2019

@author: spavko
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
import time

from sklearn.metrics import roc_curve, auc

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier

# Load the dataset from excel file

df = pd.read_excel('../data/default-of-credit-card-clients', skiprows=1)









 